# Site settings
title: Nasser Almalhawi
description: A little about me
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Nasser Almalhawi
user_description: Cloud Infrastructure Engineer, love building servers and shipping containers. 
user_title: Cloud Infrastructure Engineer
email: almalhawi.nasser@gmail.com
# twitter_username: lorem_ipsum
instagram_username: cchance_25
#facebook_username: mauricio.urraco
linkedin_username: nasser-almalhawi-112907144
github_username:  cchance25
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
